server:
  port: 8080

spring:
  application:
    name: PIPELINE-SERVICE
  spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        show_sql: false

  datasource:
    url: jdbc:mariadb://localhost:3306/maven_pipeline
    username: root
    password:
    driverClassName: org.mariadb.jdbc.Driver

